Added install script & documentation for installing this repository.
DealerDirect/php-qa-tools pull request #3
Opened 2016-10-25 14:18 UTC by frenck

2016-10-25 19:08 UTC, Potherca requested changes

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +
Even though this script does not pipe anything, I would recommend adding

```
set -o pipefail
```

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +  echo "PHP is not found, installation aborted!"
If this is an error it should be redirected to `STDERR`

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +  exit 1
As there is more than one exit scenario I would prefer to see [a different exit code](http://www.tldp.org/LDP/abs/html/exitcodes.html) than `1`

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +# Ensure Composer is installed/updated
Instead of a comment it might be better to have a function named `ensureComposerInstalled`

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +  echo "*** Installing Composer ***"
Instead of having a personal standard for messages I would prefer to see a convention being used. (For instance [the Heroku output formats](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/common.sh#L18)).

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
For various reasons I would advise against using PHP here. Why not just use bash? (Or build the whole thing in PHP).

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +      rm composer-setup.php
It would be more robust to add the `rm` to a cleanup function called from an [EXIT trap](https://linux.die.net/Bash-Beginners-Guide/sect_12_02.html).
(This would also avoid having 2 duplicate lines for removing the file).

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +fi
I would prefer to see an explicit `exit 0;`

2016-10-25 19:08 UTC, Potherca commented on README.md
> +    "** your requirements **": "*"
I would suggest using `…` instead of `"** your requirements **": "*"`.

2016-10-25 19:08 UTC, Potherca commented on README.md
> +Or modify your `composer.json` to include `dealerdirect/qa-tools` in the `require-dev` sections.
I'm not sure we should advise people to edit their `composer.json` file as this is considered a bad practice.

2016-10-25 19:08 UTC, Potherca commented on README.md
> +This is a simple metapackage, but still can be used in different ways.
Sentence is crooked. Either

> This is a simple metapackage, but it still can be used in different ways.

or

> This is a simple metapackage which can be used in different ways.

It might also be useful to list the "different ways" before going into detail. Makes it easier for people to scan ahead.

2016-10-25 19:08 UTC, Potherca commented on README.md
> +This is by far the easiest and most convenient method. Simply having all the tools available system wide.
This speaks of a personal preference. I would prefer the tone to convey a [neutral point of view](https://en.wikipedia.org/wiki/Wikipedia:Neutral_point_of_view)

2016-10-25 19:08 UTC, Potherca commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
I don't like telling people to pipe/redirect atbitrary code to bash. I also don't have any real alternative.. Other than [`maybe`](https://github.com/p-e-w/maybe) (which is not stable) or [more work than it might be worth](https://github.com/fisherman/fisherman/issues/90).

Maybe @brammittendorff might have a suggestion?

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +set -eu
I would prefer seeing the more verbose `set -o errexit` as that is a bit more understandable than `-e` (and `set -o nounset` rather than `-u`). It would also be helpful to add a comment after each flag for developers less familiar with bash.

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +      "$(curl -S https://composer.github.io/installer.sig)" = \
👍

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +      sudo mv composer /usr/local/bin/composer
Not entirly sure about the `sudo`, then again, `chown`ing would probably also require sudo, so... meh.

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +if grep -q -F "export COMPOSER_HOME=$HOME/.composer" "$HOME/.profile"; then
These two `if`s belong in an `else`. If we've just created the file it does not make sense to grep it.

2016-10-25 19:08 UTC, Potherca commented on bin/install.sh
> +source "$HOME/.profile"
This _could_ have unintended side-effects, depending on what the user has (been told by other programs to) put in their `.profile`

2016-10-25 19:08 UTC, Potherca commented on README.md
> +Or modify your `composer.json` to include `dealerdirect/qa-tools` in the `require-dev` sections.
I would strongly suggest reading [the bashstyle](https://github.com/progrium/bashstyle) for some general pointers (including "all code should go in a function").

2016-10-25 19:10 UTC, Potherca commented
I would strongly suggest reading [the bashstyle](https://github.com/progrium/bashstyle) for some general pointers (including "all code should go in a function").

2016-10-25 20:37 UTC, frenck commented on bin/install.sh
> +set -eu
👍  Agreed

2016-10-25 20:38 UTC, frenck commented on bin/install.sh
> +
👍

2016-10-25 20:38 UTC, frenck commented on bin/install.sh
> +  echo "PHP is not found, installation aborted!"
👍

2016-10-25 20:41 UTC, frenck commented on bin/install.sh
> +# Ensure Composer is installed/updated
I tried to keep it simple, top down. But I agree as well... 👍

2016-10-25 20:42 UTC, frenck commented on bin/install.sh
> +  echo "*** Installing Composer ***"
Yeah... Since we don't have a convention for it yet... Nevertheless, nice link, will "borrow" some. 😉

2016-10-25 20:45 UTC, frenck commented on bin/install.sh
> +  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
This is taken directly from the official Composer documentation. I do agree, nevertheless, this is how it is documented by Composer (which has changed a lot in the last couple of years).

2016-10-25 20:46 UTC, frenck commented on bin/install.sh
> +      sudo mv composer /usr/local/bin/composer
🎱

2016-10-25 20:48 UTC, frenck commented on bin/install.sh
> +      rm composer-setup.php
Some catches with using a trap, but in this case, yeah... 👍

2016-10-25 20:51 UTC, frenck commented on bin/install.sh
> +source "$HOME/.profile"
It "should not", but I like the don't assume approach. Replacing it with a success message at the end including an instruction would make more sense I guess. 👍

2016-10-25 20:52 UTC, Potherca commented on bin/install.sh
> +      sudo mv composer /usr/local/bin/composer
It has been decided: 
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/8BallTweets">@8BallTweets</a> Should we use `sudo mv`?</p>&mdash; 422 - Unprocessable (@potherca) <a href="https://twitter.com/potherca/status/791019040613470208">October 25, 2016</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="und" dir="ltr"><a href="https://twitter.com/potherca">@potherca</a> - Yes</p>&mdash; Ask the Magic 8 Ball (@8BallTweets) <a href="https://twitter.com/8BallTweets/status/791019196452921346">October 25, 2016</a></blockquote>

2016-10-25 20:56 UTC, Potherca commented on bin/install.sh
> +source "$HOME/.profile"
You could also just run the `export COMPOSER_HOME=$HOME/.composer` and/or `export PATH=$PATH:\$COMPOSER_HOME/vendor/bin` in the relevant `if` to have the same effect.

2016-10-25 20:59 UTC, frenck commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
I totally know where you are going here... this discussion is probably older than Netscape v.s. Mosaic...

This was based on how other larger tools do this (e.g. Composer, Homebrew). In my point of view, it's all about trust. We have a review process and the code is opensource. Take a look and decide. I would suggest adding a notice or warning above this instruction.

2016-10-25 21:02 UTC, frenck commented on README.md
> +Or modify your `composer.json` to include `dealerdirect/qa-tools` in the `require-dev` sections.
Since some people still do (including myself... opinions...) I would suggest adding something like: "prefered method" to the first instruction.

2016-10-25 21:04 UTC, frenck commented on README.md
> +    "** your requirements **": "*"
I actually changed this one during dev a couple of times. I even used a working symfony example. Not sure what to use. `...` is fine by me.

2016-10-25 21:05 UTC, Potherca commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
The alternative would be to tell people to install composer themselves which would kind of defeat the purpose of the script 😞

2016-10-25 21:05 UTC, frenck commented on bin/install.sh
> +source "$HOME/.profile"
Even better 👍

2016-10-25 21:11 UTC, Potherca commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
I guess that warning people and telling them how to do it "safely" _should_ be sufficient (like [expressed here](https://gist.github.com/btm/6700524).

It would also help to sign commits and have 2FA required for direct contributors. (As a means for more trust).

2016-10-25 21:19 UTC, frenck commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
Nice find! Will do a similar thing 👍 

I totally agree on the last bit... little out of scope for this pull request. Sound like a 'guide'. Let's discuss this post daily and consider enforcing it.

2016-10-26 07:13 UTC, brammittendorff commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
Why not use:
```
wget -O install.sh https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh
bash install.sh
```

Yes you will split it up but you will let the user decide if he wants to see the file with:
```
cat install.sh
```

You will give the power to the user to check that file for security reasons.

2016-10-26 07:45 UTC, Potherca commented on README.md
> +Or modify your `composer.json` to include `dealerdirect/qa-tools` in the `require-dev` sections.
Agree with the wording "preferred method".

2016-10-26 23:21 UTC, frenck commented on bin/install.sh
> +source "$HOME/.profile"
Regarding your last comment... actually, you can't...

2016-10-27 08:36 UTC, frenck commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
@Potherca This is also a way of doing it. 
https://rvm.io/rvm/security
They offer it as en extra installation method.

2016-10-27 08:50 UTC, Potherca commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
I think that is about as safe as we can make it without making it _too_ difficult for common users.

2016-10-27 10:22 UTC, frenck commented
@Potherca Updated PR.
Left out GPG, since that requires some more internal organisation (like determining how we are going to distribute a keyring or use a organisation wide key with developer sub-keys....)

2016-10-27 12:07 UTC, brammittendorff commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
@frenck even better

2016-10-27 12:38 UTC, Potherca approved these changes

2016-10-27 12:39 UTC, Potherca commented
:+1:

2016-10-27 12:41 UTC, Potherca commented on README.md
> +composer require --dev "dealerdirect/qa-tools:*"
The star is not needed `composer require --dev "dealerdirect/qa-tools` would just grab the latest version. (Taking constraints into account).

2016-10-27 12:41 UTC, Potherca commented on README.md
> +    "dealerdirect/qa-tools": "*"
We might want to add a version number rather than "no constraint"

2016-10-27 12:52 UTC, frenck commented on README.md
> +bash <(curl -S https://raw.githubusercontent.com/DealerDirect/php-qa-tools/master/bin/install.sh)
@Potherca @brammittendorff added GPG.

2016-10-27 12:56 UTC, merged